# Generated by Django 3.1.4 on 2020-12-06 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SuSheInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ssid', models.CharField(max_length=10, verbose_name='宿舍号')),
                ('lv', models.IntegerField(verbose_name='宿舍楼层')),
                ('size', models.IntegerField(choices=[(2, '2人/间'), (4, '4/人间'), (6, '6/人间')], verbose_name='宿舍容量')),
                ('extra', models.TextField(default='暂无', verbose_name='其他信息')),
            ],
            options={
                'verbose_name': '宿舍基本信息',
                'verbose_name_plural': '宿舍基本信息',
                'ordering': ['lv', 'ssid'],
            },
        ),
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sid', models.CharField(max_length=20, verbose_name='学号')),
                ('name', models.CharField(max_length=50, verbose_name='姓名')),
                ('campus', models.IntegerField(choices=[(0, '计算机科学学院'), (1, '理学院'), (2, '文学院'), (3, '纺织学院'), (4, '环境学院'), (5, '城市学院'), (6, '艺术学院')], verbose_name='学院')),
                ('major', models.CharField(max_length=50, verbose_name='专业')),
                ('phone', models.CharField(max_length=20, verbose_name='手机')),
                ('gender', models.BooleanField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别')),
                ('ssid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='宿舍', to='app.susheinfo', verbose_name='宿舍')),
            ],
            options={
                'verbose_name': '学生基本信息',
                'verbose_name_plural': '学生基本信息',
                'ordering': ['sid'],
            },
        ),
    ]
